### ISSUE TITLE
Migrating to Null Safety

### ISSUE THREAD

**Issue by are** [shamblett/cbor#14]
Are there plans to migrate to null safety soon?

**Comment by shamblett** [comment]
In short yes, I've been keeping my eye on null safety for all my packages not just this one, I would prefer to migrate when null safety officially lands in Dart as I only develop packages against stable Dart builds not dev ones. I need to re read the the migration docs to see when this could best be done. I maintain 15 packages in all and they all need to be migrated.

If you have a particular need for this there's no reason why cbor can't be the first, or indeed if you wish to have a look at this yourself feel free, pull requests gratefully accepted.

**Comment by shamblett** [comment]
Package cbor 3.3.0-nullsafety.0 released.

**Comment by shamblett** [comment]
Package re released at version 4.0.0 incorporating version 2.12 of Dart and null safety
