### ISSUE TITLE
Any plans to support custom types?

### ISSUE THREAD

**Issue by isoos** [shamblett/cbor#61]
I think CBOR specification allows the definition of custom types. Do you have any plan to support them?

**Comment by shamblett** [comment]
This is not part of RFC 8949 that I can see, it seems to be documented[ here](https://cbor2.readthedocs.io/en/latest/customizing.html)  as part of the CBOR2 Python library so at the moment no, there is no plan to support this functionality.

**Comment by isoos** [comment]
Right, makes sense. So, if I have `Uint16List` or similar structure, the recommendation is to convert it to `Uint8List` and then `CborBytes`, right?

**Comment by shamblett** [comment]
Not sure you need to convert it to Uint8List, CborBytes takes a List<int> so you should be OK with UInt16List as is.
